"""Story chapter title cards ("熱血高校ストーリー『…』の巻"): BG1 text drawn from an
uncompressed 4bpp tileset (tiles 0x200-0x3FF at ROM 0x0A4000, palette 1: colour 1 white,
colour 5 black). The tilemap is generated by the game, so the Korean text is rendered into
the very tiles each text cell uses: translations/titles.csv lists, per text line, the tile
of every column of its top and bottom row ('-' for a cell that cannot be redrawn)."""
from tools.kbb import encode, glyphs, sprtext

TILESET_ROM = 0x0A4000
FIRST_TILE = 0x200
INK, BG = 1, 5


class TitleError(Exception):
    pass


def render_line(text, cols):
    """16 x (cols*8) ink matrix: Galmuri11 text centred, 12px advance, 6px spaces."""
    width = sum(encode.SPACE_W if c == " " else glyphs.render(c)[0] for c in text if c == " " or glyphs.render(c))
    px = [[0] * (cols * 8) for _ in range(16)]
    x = max(0, (cols * 8 - width) // 2)
    for c in text:
        if c == " ":
            x += encode.SPACE_W
            continue
        g = glyphs.render(c)
        if g is None:
            continue
        dw, cell = g
        for y in range(16):
            for i in range(16):
                if x + i < cols * 8 and (cell[y] >> (15 - i)) & 1:
                    px[y][x + i] = 1
        x += dw
    return px


def apply(rom, rows):
    """Draw each translated line into its tiles (in place); returns the number of lines drawn."""
    done = 0
    for r in rows:
        if not r.get("korean"):
            continue
        top, bottom = r["top"].split(), r["bottom"].split()
        if len(top) != len(bottom):
            raise TitleError("row lengths differ: %s" % r.get("id"))
        px = render_line(r["korean"], len(top))
        for c, (t, b) in enumerate(zip(top, bottom)):
            for tid, y0 in ((t, 0), (b, 8)):
                if tid == "-":
                    continue
                tile = int(tid, 16)
                if not FIRST_TILE <= tile < 0x400:
                    raise TitleError("tile %s outside the title tileset" % tid)
                data = sprtext.encode4([[INK if px[y0 + y][c * 8 + x] else BG for x in range(8)] for y in range(8)])
                off = TILESET_ROM + (tile - FIRST_TILE) * 32
                rom[off:off + 32] = data
        done += 1
    return done
